"""
Service responsible for chat completion.
"""

import logging

from app.llm.chat_factory import ChatFactory

logger = logging.getLogger(__name__)


class ChatCompletionService:
    """
    Service responsible for generating responses from the LLM.
    """

    def __init__(self) -> None:

        self.provider = ChatFactory.create()

        logger.info(
            "Chat Completion Service initialized."
        )

    def generate_response(
        self,
        prompt: str,
    ) -> str:
        """
        Generate an LLM response.

        Args:
            prompt:
                Prompt generated by Prompt Builder.

        Returns:
            Generated response.
        """

        return self.provider.generate_response(prompt)