"""
Service responsible for chat completion.
"""

import logging
import time

from app.exceptions.chat_completion_exceptions import ChatException
from app.llm.chat_factory import ChatFactory

logger = logging.getLogger(__name__)


class ChatCompletionService:
    """
    Service responsible for generating responses
    from the configured LLM provider.
    """

    def __init__(self) -> None:

        self._provider = ChatFactory.create()

        logger.info(
            "Chat Completion Service initialized."
        )

    def generate_response(
        self,
        prompt: str,
    ) -> str:
        """
        Generate a response from the configured LLM.

        Args:
            prompt:
                Prompt generated by Prompt Builder.

        Returns:
            Generated response text.
        """

        logger.info("Starting chat completion.")

        self._validate_prompt(prompt)

        logger.info(
            "Prompt Length=%d characters",
            len(prompt),
        )

        start_time = time.perf_counter()

        response = self._provider.generate_response(prompt)

        execution_time = time.perf_counter() - start_time

        logger.info(
            "Chat completion successful | "
            "Response Length=%d | "
            "Execution Time=%.3fs",
            len(response),
            execution_time,
        )

        return response

    @staticmethod
    def _validate_prompt(
        prompt: str,
    ) -> None:
        """
        Validate the prompt.

        Args:
            prompt:
                Prompt to validate.

        Raises:
            ChatException:
                If the prompt is invalid.
        """

        if prompt is None:

            logger.error(
                "Prompt is None."
            )

            raise ChatException(
                "Prompt cannot be None."
            )

        if not prompt.strip():

            logger.error(
                "Prompt is empty."
            )

            raise ChatException(
                "Prompt cannot be empty."
            )

        if len(prompt) > 50000:

            logger.error(
                "Prompt exceeds maximum allowed length."
            )

            raise ChatException(
                "Prompt exceeds the maximum allowed length."
            )